### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by alex-ju** [gov-ithub/govro-design#1]
Propuneti tool-urile de UX/UI cu care ati lucrat sau vreti sa lucram in cardul GovITHub.

**Comment by sandriu** [comment]
Cred că tool-urile de UX/UI folosite sunt mai puțin importante.
Dacă ești profesionist, îți faci treaba la fel de bine și în Axure sau Invision (sau alte tool-uri de UX), și în Photoshop sau Sketch (sau alte tool-uri de UI).

**Comment by anodpixels** [comment]
Aici conteaza cat de organizat esti in aceste tool-uri si cum faci hand-off catre altii, fie PSD sau Sketch, organizate, explicite si share-uite cum trebuie.
Aici problema nu sunt tool-urile ci fisierele pe care le livram, in ce format livram, trebuie sa impunem un standar.

> Ca idee, Adobe Photoshop este cel mai vechi cel mai extins (si pe WINDOWS), sa tinem minte Romania abia a inceput sa accepte MacBook-urile si ecosistemul macOS.
