### ISSUE TITLE
Componente vizuale UI

### ISSUE THREAD

**Issue by alex-ju** [gov-ithub/govro-design#12]
Avem nevoie cât mai curând de propuneri de cum să arate [componentele de UI](https://gov-ithub.github.io/govro-design/componente/).
Cine dorește să contribuie poate trimite propuneri de draft-uri ca răspuns la acest issue.

**Comment by anodpixels** [comment]
Perfect, mersi @alex-ju pentru Issue voi revenii cu o propunere cat mai repede.

**Comment by anodpixels** [comment]
@alex-ju dupa cum ti-am promis, atasat gasesti previw-uri si un ZIP cu primul draft din styleguide ce contine:
- .PSD-ul cu artboarduri
_(Photoshop CS6 nu il va citii trebuie CC nu am reusit sa-l fac compatibil inca)_
- grid (mobile, tablet-portrait, tablet-landscape, desktop)
- reguli de tipografie
- stiluri de tipografie
- elemente ui de baza
+ o asezare in pagina a fonturilor (cea cu imaginea lui Dacian Ciolos)

![colors](https://cloud.githubusercontent.com/assets/690264/20584428/1cfd21b6-b1fb-11e6-8c39-13aa25ff0312.png)
![desktop](https://cloud.githubusercontent.com/assets/690264/20584427/1cfbf7e6-b1fb-11e6-892c-099db195e283.png)
![mobile](https://cloud.githubusercontent.com/assets/690264/20584430/1cff17a0-b1fb-11e6-9d57-95b23a0fc140.png)
![tablet-1](https://cloud.githubusercontent.com/assets/690264/20584429/1cfd97ae-b1fb-11e6-9baf-5243cbf40a4e.png)
![tablet](https://cloud.githubusercontent.com/assets/690264/20584431/1d027968-b1fb-11e6-906f-4a94c4d3d308.png)
![ui-elements](https://cloud.githubusercontent.com/assets/690264/20584432/1d16ffbe-b1fb-11e6-8f48-f17ba3f66396.png)
![gov-ro-fonts-03](https://cloud.githubusercontent.com/assets/690264/20584448/442d78e4-b1fb-11e6-9c20-7b93a28c070d.png)
[gov-ro-styleguide-draft1.zip](https://github.com/gov-ithub/govro-design/files/610345/gov-ro-styleguide-draft1.zip)

**Comment by alex-ju** [comment]
Mersi @anodpixels pentru efortul depus! Asteptam feedback de la colegi si comunitate.

**Comment by cezarneaga** [comment]
Nice. Hai sa facem rapid un revamp la blogul guvernului cu designul asta

**Comment by mottanu** [comment]
typography-ul mi se pare foarte bun. La inputuri, albastrul mi se pare un picut prea puternic. De asemenea, verdele poate putin mai inchis. Aceeasi culoare, dar alt ton. In rest, I really like it! Congrats @anodpixels

**Comment by anodpixels** [comment]
Thanks guys for the feedback!
@mottanu stiu ce zici doar ca timpul meu a fost putin limitat, as fi vrut sa fac si eu default header si footer le-am gandit but no time, voi mai revenii luni cu imbunatatiri

**Comment by LigiaAdam** [comment]
Very nice! Cred ca mai trebuie inclus si-un icon pentru  comentarii

**Comment by sandriu** [comment]
Am văzut că @anodpixels a propus 2 typeface-uri: "Work Sans" pentru body text și "Noto Serif" pentru titluri.

Am testat cele 2 typeface-uri pe instanța mea locală de dexonline, pentru a verifica afișarea corectă a diacriticelor din română. Cuvântul "cârciumă" a fost unul din cuvintele de referință când am ales un font pentru dexonline.ro prietenos cu diacriticele românești (noi și vechi), așa că testele le-am făcut pe același cuvânt.

Atașez screenshot-uri:
- "Work Sans" este ok:
![screenshot_2016-11-24_dexonline-local-work-sans](https://cloud.githubusercontent.com/assets/1265882/20607191/f79fe334-b27e-11e6-9e98-f5e14abf9ab9.png)

- comparație cu producția (dexonline.ro), unde folosim "Open Sans":
![screenshot_2016-11-24_dexonline-productie-open-sans](https://cloud.githubusercontent.com/assets/1265882/20607208/0c64390a-b27f-11e6-838c-b522017adea3.png)

- "Noto Serif" creează probleme la textele scrise cu CAPS, la diacriticile vechi (vedeți a cincea definiție din screenshot):
![screenshot_2016-11-24_dexonline-local-noto-serif](https://cloud.githubusercontent.com/assets/1265882/20607255/686ebbda-b27f-11e6-80da-6b9271fa58d0.png)

**Comment by anodpixels** [comment]
@sandriu m-am uitat peste teste, acestea vor depinde totdeuna de computer, de motoru de randare a fontului windows,mac, linix si de densitatea pixelirol pe ecran, prefer un font mai intregit si mai corpolent decat shape-uri subtiri precum Open Sans.

De comportament vad ca se țin bine amandoua si nu au nicio problema deci ar fi doar ideea de randare dar asta nu o putem controla, iar fonturile foarte subțiri au efectul de "sârmă" pe windows devenind foarte pixelate uneori, asa ceva un pic mai dens ne mai salvează.

Mersi mult de test.

**Comment by alex-ju** [comment]
@anodpixels asteptam un update de la tine pentru restul componentelor

**Comment by anodpixels** [comment]
@alex-ju revin cu un update, atasat gasesti preveiw-uri si un .ZIP cu styleguide ce contine:
la aceasta versiune, conform unei convorbiri cu @sandriu am propus sa incep sa fac si un header/footer default pentru (poate) un urmator update al site-ului gov.ro.
Pe langa acestea am gandit si un default header-bar (acuma ca scriu ma gandesc ca mergea si un footer) care sa fie inclus in restul proiectelor produse de voi deasupra la tot, poate va ajuta si unifica putin proiectele.

.PSD-ul cu artboard-uri
_(Photoshop CS6 nu il va citii trebuie CC nu am reusit sa-l fac compatibil inca)

- grid (mobile, tablet-portrait, tablet-landscape, desktop)_
- culorile de baza
- sistem de umbre (pt a fi folosit la hoveruri, pop-ups, overlay, modale)
- reguli de tipografie
- stiluri de tipografie
- elemente ui (am adaugat checkboxe, radio, butoane secundare, dropdown menu, alerte, stil link extern, stil link pe imagine care este inca in lucru).

[gov-ro-styleguide-12dec.zip](https://github.com/gov-ithub/govro-design/files/644955/gov-ro-styleguide-12dec.zip)
![header-footer](https://cloud.githubusercontent.com/assets/690264/21085435/c6d24432-c01a-11e6-818d-75d5708cc767.png)
![ui-elements](https://cloud.githubusercontent.com/assets/690264/21085434/c6d19780-c01a-11e6-88df-13490154bfaa.png)

**Comment by sandriu** [comment]
Am văzut pe Slack pe canalul general că se vorbea de construirea unei teme Wordpress, care să rămână a Guvernului și să poată fi folosită _pe bandă rulantă_ pentru cât mai multe site-uri de prezentare/de ministere. Temele Wordpress din comerț au dezavantajul că cer o licență nouă ($) pentru fiecare refolosire.

Dacă mai apucăm să construim acea temă de Wordpress, mi-ar plăcea ca styleguide-ul să fie implementat în tema respectivă.

**Comment by mottanu** [comment]
@sandriu total de acord.
