### ISSUE TITLE
Principii de UX

### ISSUE THREAD

**Issue by alex-ju** [gov-ithub/govro-design#13]
Cine dorește să contribuie la setul de [principii de UX](https://gov-ithub.github.io/govro-design/principii/ux/) poate răspunde la acest issue, poate adauga un nou issue sau poate trimite direct un pull request.

**Comment by sandriu** [comment]
Pagina cu principii de UX ar trebui să conțină:

- [ ] definiția user experience-ului (UX), pentru a se elimina confuzia dintre UX și UI;
- [ ] definiția user experience design-ului (UXD), pentru a se elimina confuzia celor care cred că UX presupune doar crearea de wireframes;
- [ ] definiția și atribuțiile unui user experience designer, pentru a se elimina confuzia celor care cred că se pricep la "UX/UI", când de fapt se pricep doar la "UI";
- [ ] cele mai importante principii de IA (arhitectura informației), cu exemple de aplicare;
- [ ] cele mai importante 5-6 principii de interaction design, preferabil cu exemple de aplicare (sau măcar link-uri);
- [ ] cele mai importante 5-6 principii de psihologie aplicată în web, preferabil cu exemple de aplicare;
- [ ] cele mai importante 5-6 principii de usability, preferabil cu exemple de aplicare;

Nu știu dacă are rost să intrăm în principii de product design, prototyping, content strategy, fiindcă riscăm să facem prea greoaie partea de teorie. Și oricum doar citind câteva rânduri despre aceste 3 domenii nu-ți poate oferi o cunoaștere suficientă a acestora. **Corectați-mă dacă greșesc.**

**Vă rog propuneți și alte capitole pentru pagina de UX, dacă considerați structura de mai sus insuficientă**.

**Comment by sandriu** [comment]
Ultimul meu pull-request conține capitolele de _UX research_ și _Interaction design_ (https://github.com/gov-ithub/govro-design/pull/17).

**Comment by sandriu** [comment]
Ar mai fi de adăugat capitolul de _Usability_ (am vorbit cu @dragosdumitrascu și mâine el va trimite ceea ce a scris până acum pentru acest capitol).
Capitolul de psihologie aplicată în web rămâne opțional.

**Comment by sandriu** [comment]
Aviz celor care vor să mai contribuie cu conținut pentru pagina de UX: 
- eu personal am păstrat mulți termeni în engleză, în loc să-i traduc ciudat sau incomplet; i-am formatat în schimb cu italic, ca să se știe că e vorba de termenii originali, în engleză (sunt mai ușor de găsit în literatura de specialitate astfel, pentru cei care doresc extra documentare în domeniu); 
- am specificat bibliografie pentru fiecare paragraf în parte, formatat ca "[x]", unde "x" este numărul sursei din bibliografie.

De dragul consecvenței în pagina UX, cred că și ceilalți contribuitori ar fi bine să respecte criteriile de mai sus.

**Comment by sandriu** [comment]
Am introdus recent ideea de checklist în pagina de "Principii de UX". Un checklist arată așa:

![exemplu de checklist](https://cloud.githubusercontent.com/assets/1265882/21154889/b62458aa-c178-11e6-8dda-35ad5b837c68.png)

și are rolul de a ajuta cititorul să bifeze rapid toți pașii parcurși în "algoritmul" descris în acel checklist.

Ideea mi-a venit făcând paralela cu unele site-uri de rețete culinare care afișează lista ingredientelor necesare sub formă de checklist (fiecare ingredient putând fi bifat pe măsură ce-l pui în coșul de cumpărături - funcție foarte utilă dacă nu ți-ai notat pe hârtie cele necesare înainte de a ajunge la magazin).

Indicat ar fi să organizăm bucăți cât mai mari de teorie în checklist-uri, astfel încât cititorii să învețe cât mai repede "algoritmii" prezentați (metodologiile).
Iarăși indicat ar fi ca checklist-urile să fie colorate special, ca să sară puțin în ochi față de restul paragrafelor de teorie.

**Comment by sandriu** [comment]
Câteva sfaturi pentru formatarea textului în styleguide:
- lista de tip "checklist" trebuie să conțină `<input type="checkbox">` în fața fiecărui item, pentru a afișa un checkbox funcțional;
- listele simple conțin doar caracterul `*[spațiu]` în fața fiecărui item;
- listele ce conțin subliste sunt scrise ca:
```
*[spațiu]item 1 listă părinte:
[spațiu][spațiu]* item 1 sublistă
[spațiu][spațiu]* item 2 sublistă
```
