### ISSUE TITLE
Resurse

### ISSUE THREAD

**Issue by dragosdumitrascu** [gov-ithub/govro-design#2]
va rog adaugati resursele existente (logo vectorial, guidelines, etc )

**Comment by alex-ju** [comment]
Momentan exista cele 3 resurse de mai jos, cu mentiunea ca ghidul de indentitate vizuala este in curs de actualizare de catre echipa noastra (dar regulile de aliniere, spatiere, etc vor ramane aceleasi)
[sigla gov.svg.zip](https://github.com/gov-ithub/govro-design/files/577655/sigla.gov.svg.zip)
[sigla govithub.svg.zip](https://github.com/gov-ithub/govro-design/files/577656/sigla.govithub.svg.zip)
[ghid-identitate-vizuala-gov-ro.pdf](https://github.com/gov-ithub/govro-design/files/577658/Ghid-identitate-vizuala-gov-ro.pdf)
